package main

import (
	"encoding/gob"
	"io"
	"log"
	"os"
	"sync"
)

/**
*****************************
***********NOTE**************
*****************************
This blocking store is not used, but only kept for reference and comparison
This blocking store is replaced by store.go implemented with non-blocking channels
**/

// struct is collection of fields whereas interface type is a set of method signature
// Go doesn't have class but you can define methods on types
/**
method vs function: methods are functions with a special receiver argument. For example:
func (v Vertex) Abs() float64 {
	return math.Sqrt(v.X*v.X + v.Y*v.Y)
}
ref: https://go.dev/tour
*/

type URLStoreBlcoking struct {
	urls map[string]string
	mu   sync.RWMutex
	file *os.File
}


func NewURLStoreBlocking(filename string) *URLStoreBlcoking {
	// maps are reference type
	// new just allocates memory, not initializes memory; make allocates and initializes memory
	s := &URLStoreBlcoking{urls: make(map[string]string)}
	f, err := os.OpenFile(filename, os.O_RDWR|os.O_CREATE|os.O_APPEND, 0644)
	if err != nil {
		log.Fatal("URLStore:", err)
	}
	s.file = f
	if err := s.loadBlocking(); err != nil {
		log.Println("Error while loading the URLStore:", err)
	}
	return s
}

/**
Methods with pointer receivers can modify the value to which the receiver points (as Scale does here).
Since methods often need to modify their receiver, pointer receivers are more common than value receivers.
ref: https://go.dev/tour
*/
func (s *URLStoreBlcoking) GetBlocking(key string) string {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.urls[key]
}

func (s *URLStoreBlcoking) SetBlocking(key, url string) bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	// if _, ok pattern
	if _, present := s.urls[key]; present {
		return false
	}
	s.urls[key] = url
	return true
}


func (s *URLStoreBlcoking) saveBlocking(key, url string) error {
	e := gob.NewEncoder(s.file)
	return e.Encode(record{key, url})
}


func (s *URLStoreBlcoking) PutBlocking(url string) string {
	// for {} is infinite loop so there must be something inside the loop to break out of the loop
	// this for loop keeps trying until a unique key is generated by genbKey
	// for existing keys, our Set method will return false, so the loop will continue
	for {
		key := genKey()
		if ok := s.SetBlocking(key, url); ok {
			if err := s.saveBlocking(key, url); err != nil {
				log.Println("Error putting data in URLStore:", err)
			}
			return key
		}

	}
	panic("shouldn't get here")
}


func (s *URLStoreBlcoking) loadBlocking() error {
	if _, err := s.file.Seek(0,0); err != nil {
		return err
	}
	d := gob.NewDecoder(s.file)
	var err error 
	for err == nil {
		var r record
		if err = d.Decode(&r); err == nil {
			s.SetBlocking(r.key, r.URL)
		}
	}
	if err == io.EOF {
		return nil
	}
	return err
}
